---
title: Analyse du jeu de données final
---

```{python}
#|echo: false
{{< include code_snippets/_import-packages.py >}}

```

## Chargement du jeu de données

```{python}
suggestion_df = tools.load_intermediate_data("save_before_analysis")
```

Maintenant que j'ai un jeu de données sans valeurs manquantes. Je visualise la répartition des produits dans les différentes catégories.
En effet pour que le moteur de suggestion de valeurs nutritionnelles soit performant il faut que les catégories de produit soient bien distinctes.

### Description

Rapidement je visualise le contenu des colonnes du jeu de données.

```{python}
suggestion_df.describe(include="all").round(2)
```

### Répartition

Quelle catégorie est la plus représentée ?

```{python}
fig = px.pie(suggestion_df, names="pnns_groups_1", title="Répartition des catégories de produit du jeu de données")
fig.show()
```

```{python}
# Calculer le pourcentage des produits par catégorie
category_counts = suggestion_df["pnns_groups_1"].value_counts(normalize=True).round(4) * 100
category_counts = category_counts.reset_index()
category_counts.columns = ["pnns_groups_1", "pourcentage"]

# Créer le graphique avec px.bar
fig = px.bar(
    category_counts,
    x="pnns_groups_1",
    y="pourcentage",
    color="pnns_groups_1",
    text_auto=".2f",  # Afficher les valeurs avec 2 décimales
    title="Répartition des produits par catégorie en pourcentage",
).update_xaxes(categoryorder="total descending")

fig.show()

```

Les produits sucrés sont représentés en majorités dans le jeu de données.

### Distribution

Est ce que des catégories de produits ont des distributions similaires en fonction de leurs caractéristiques nutritionnelles ?

```{python}
col_100g = [col for col in suggestion_df.columns if col not in ["code", "pnns_groups_1"]]
```

```{python}
tools.histogram_features(suggestion_df, col_100g)
```

Les valeurs nutritives des produits sont distribuées avec une asymétrie vers la droite.

Analyse de la distribution des catégories de produits par valeurs nutritive.

```{python}
import plotly.figure_factory as ff

# Créer un pivot table pour restructurer les données
groups_df = suggestion_df.groupby("pnns_groups_1")[col_100g]

# Liste des groupes uniques
group_labels = suggestion_df["pnns_groups_1"].unique()

for col in col_100g:
    fig = px.box(
        suggestion_df,
        x=col,
        y="pnns_groups_1",
        color="pnns_groups_1",
        points=False,
        width=800,
        height=600,
        title=f"Distribution de {col} par pnns_groups_1",
    )

    for group_label in group_labels:
        fig.add_annotation(
            x=-0,
            y=group_label,
            text=f"(n={(len(groups_df.get_group(group_label)[col]))})",
            yshift=-20,
            showarrow=False,
        )

    fig.update_traces(
        boxmean=True,
        boxpoints=False,  # outliers, suspectedoutliers
    )
    fig.update_layout(
        xaxis_tickformat=",.2f",
        boxgroupgap=0.5,
    )

    fig.show()

    hist_data = [group_df[col] for _, group_df in groups_df]

    fig = ff.create_distplot(
        hist_data,
        group_labels,
        show_hist=False,
        show_rug=False,
    )
    fig.update_layout(
        title_text=f"Distribution KDE de {col} par groupe de produits",
        xaxis_title=col,
        yaxis_title="Densité",
    )
    fig.show()

```

Les 2 jeux de graphiques précédents révèlent que un produit sucrés présentent majoritairement du sucre. Et les produits salés un fort de sel.

Certaines catégories ont l'air similaires.

### Matrice de corrélation

Les distributions des colonnes ne sont pas normales. Le calcul des corrélations est réalisé avec spearman.

```{python}
df_corr = suggestion_df[col_100g].corr(method="spearman").round(2)
# Mask to matrix
mask = np.triu(np.ones_like(df_corr, dtype=bool))

# Viz
df_corr_viz = df_corr.mask(mask).dropna(how="all").dropna(axis="columns", how="all")

fig = px.imshow(
    df_corr_viz,
    text_auto=True,
    zmin=-1,
    zmax=1,
    color_continuous_scale="RdBu_r",
    title="Matrice de correlation suivant le coefficient de spearman",
)
fig.update_xaxes(showgrid=False).update_yaxes(showgrid=False)
fig.show()
```

Le coefficient de Spearman confirme la présence d'une relation monotone croissante entre `saturated-fat_100g` et `fat_100g`. La présence de graisses dans un produit implique la présence de graisses saturées. On peut assez clairement que les produits les plus énergétiques contiennent un fort taux en graisses et graisse saturées.

### Relation entre les valeurs nutritives par type de produits

Est ce que les catégories de produit sont bien distinctes ?

```{python}
fig = px.scatter_matrix(
    suggestion_df,
    dimensions=col_100g,
    width=1000,
    height=1000,
)

fig.update_traces(
    diagonal_visible=False,
    showupperhalf=False,
)

fig.show()
```

Il y a trop de variation entre les produits pour visualiser des relations entre les valeurs nutritives.

Pour simplifier la visualisation je groupe les produits par catégories et je compare leurs valeurs médianes.

```{python}
df_grouped = suggestion_df.groupby("pnns_groups_1")[col_100g].median().reset_index()

fig = px.scatter_matrix(
    df_grouped,
    dimensions=col_100g,
    color="pnns_groups_1",
    title="Relation entre valeurs nutritives par catégorie de produit",
    width=1000,
    height=1000,
)

fig.update_traces(
    diagonal_visible=False,
    showupperhalf=False,
)

fig.show()
```

Je visualise la relation entre `energy_100g` et `proteins_100g` par catégorie de produit.

```{python}
df_grouped = suggestion_df.groupby("pnns_groups_1")[["energy_100g", "proteins_100g"]].median().reset_index()

fig = px.scatter(
    df_grouped,
    x="energy_100g",
    y="proteins_100g",
    text="pnns_groups_1",
    color="pnns_groups_1",
    title="Relation entre énergie et protéines par catégorie",
    size_max=60,
)

# Ajouter les noms des catégories
fig.update_traces(textposition="top center", marker=dict(size=10))

fig.show()

```

On peut voir que les produits sucrés et salés sont plus énergétiques mais ne sont pas très protéinés.

## Analyse en composante principale

::: callout-note
L'ACP a deux objectifs principaux :

-   la variabilité entre les individus, c'est-à-dire quelles sont les différences et les ressemblances entre individus ;

-   les liaisons entre les variables : y a-t-il des groupes de variables très corrélées entre elles, qui peuvent être regroupées en de nouvelles variables synthétiques ?
:::

Ici le but de l'ACP est de déterminer si je peux réduire le nombre de valeurs nutritionnelles pour caractériser un produit.

```{python}
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
```

Distribution des valeurs nutritives avant transformation. La transformation consiste à réduire à la même échelle les colonnes du jeu de données.

Pour le moment, les échelles sont trop différentes pour réaliser une comparaison.

```{python}
from sklearn.preprocessing import StandardScaler

X = suggestion_df[col_100g]

# Standardisation des données
scaler = StandardScaler()
X_scaled = scaler.fit_transform(suggestion_df[col_100g])

# Vérifier la transformation
idx = ["mean", "std"]
X_scaled = pd.DataFrame(X_scaled, columns=col_100g)

stats = pd.DataFrame([X_scaled.mean().round(2), X_scaled.std().round(2)], index=idx)
show(stats.T, "Moyennes et écart-types des valeurs nutritives après transformation")
```

Les valeurs numériques sont correctement centrées réduites avec une moyenne de 0 et un écart-type de 1.

Il devient possible de visualiser leurs distributions sur le même graphique.

```{python}
px.histogram(
    X_scaled,
    histnorm="probability density",
    title="Distribution des valeurs nutritives après normalisation",
)
```

```{python}
from sklearn.decomposition import PCA

# Appliquer l'ACP sans fixer n_components
pca = PCA()
X_reduced = pca.fit_transform(X_scaled)
```

```{python}
# Variance expliquée en pourcentage
explained_variance_ratio = pca.explained_variance_ratio_ * 100  # En %
cumulative_variance = explained_variance_ratio.cumsum()

explained_variance = pca.explained_variance_

pca_result = pd.DataFrame({
    "Composantes principales": [f"PC{i + 1}" for i in range(len(explained_variance))],
    "Valeurs propres": explained_variance,
    "Pourcentage d'inertie (%)": explained_variance_ratio,
    "Pourcentage d'inertie cumulée (%)": cumulative_variance,
})
show(pca_result.round(2), "Résultat de l'ACP valeurs nutritives par produit")
```

Je trace les graphique en éboulis des valeurs propres pour déterminer le nombre de valeurs propres nécessaires pour décrire au mieux le jeu de données.

```{python}
# Tracé du graphique avec Plotly Express
fig = px.bar(
    pca_result,
    x="Composantes principales",
    y="Pourcentage d'inertie (%)",
    text_auto=".2f",
    title="Scree Plot (Éboulis des pourcentage d'inertie)",
)

# Ajout de la courbe cumulative
fig.add_scatter(
    x=pca_result["Composantes principales"],
    y=pca_result["Pourcentage d'inertie cumulée (%)"],
    mode="lines+markers",
    name="Pourcentage d'inertie cumulée (%)",
    line_color="red",
)

kaiser_threshold = round((100 / pca.n_components_), 2)

fig.add_hline(
    y=kaiser_threshold,
    line_dash="dash",
    line_color="pink",
    annotation_text=f"Kaiser threshold: {kaiser_threshold}",
)

# Mise en forme
fig.update_layout(
    xaxis_title="Composantes principales",
    yaxis_title="Pourcentage d'inertie (%)",
    yaxis=dict(range=[0, 100]),
    showlegend=True,
)

fig.show()

```

Méthode du coude:

```{python}
# Tracé du Scree Plot avec Plotly Express
fig = px.line(
    pca_result,
    x="Composantes principales",
    y="Valeurs propres",
    title="Valeurs propres (Méthode du coude)",
)

fig.add_hline(
    y=1,
    line_dash="dash",
    line_color="red",
    annotation_text="Kaiser threshold: 1",
)

fig.update_traces(mode="markers+lines")

fig.show()
```

::: callout-note

-   Variance expliquée cumulative (choisir un seuil de variance, souvent 85-95%).

-   Selon la méthode du coude : detection d'une chute du pourcentage d'inertie visuellement: les 5 premiers axes sont les plus importants

-   Selon le critère de Kayser : conserve les valeurs propres supérieurs à 1. On peut aussi définir le seuil limite avec la somme cumulée des valeurs propres: 100/nb components = 14.29%

:::

Selon la règle de Kaiser, il suffit de conserver les trois premières composantes pour décrire notre jeu de données sans perte d'information. Ces trois premières composantes expliquent 78 % de la variance cumulée

### Cercles de corrélation

```{python}
# Fonction de représentation graphique des Cercles des corrélations
def correlation_graph(pca, x_y, features):
    """Affiche le graphe des correlations

    Positional arguments :
    -----------------------------------
    pca : sklearn.decomposition.PCA : notre objet PCA qui a été fit
    x_y : list ou tuple : le couple x,y des plans à afficher, exemple [0,1] pour F1, F2
    features : list ou tuple : la liste des features (ie des dimensions) à représenter
    """

    # Extrait x et y
    x, y = x_y

    # Taille de l'image (en inches)
    fig, ax = plt.subplots(figsize=(10, 9))

    # Pour chaque composante :
    for i in range(0, pca.components_.shape[1]):
        # Les flèches
        ax.arrow(
            0,
            0,
            pca.components_[x, i],
            pca.components_[y, i],
            head_width=0.07,
            head_length=0.07,
            width=0.02,
        )

        # Les labels
        plt.text(pca.components_[x, i] + 0.05, pca.components_[y, i] + 0.05, features[i])

    # Affichage des lignes horizontales et verticales
    plt.plot([-1, 1], [0, 0], color="grey", ls="--")
    plt.plot([0, 0], [-1, 1], color="grey", ls="--")

    # Nom des axes, avec le pourcentage d'inertie expliqué
    plt.xlabel("F{} ({}%)".format(x + 1, round(100 * pca.explained_variance_ratio_[x], 1)))
    plt.ylabel("F{} ({}%)".format(y + 1, round(100 * pca.explained_variance_ratio_[y], 1)))

    # Affichage du titre du graphique
    plt.title("Cercle des corrélations (F{} et F{})".format(x + 1, y + 1))

    # Le cercle
    an = np.linspace(0, 2 * np.pi, 100)
    plt.plot(np.cos(an), np.sin(an))  # Add a unit circle for scale

    # Axes et display
    plt.axis("equal")
    plt.show(block=False)
```

### Réinjection des composantes principales pour faciliter la visualisation

Afin de faciliter la visualisation des produits, je réintroduis les valeurs des composantes principales obtenues précédemment grâce à l'ACP.\n Ces nouvelles variables, appelées "composantes principales", résument les informations les plus importantes des données d'origine en réduisant leur dimensionnalité.\n

```{python}
# Réinjection des axes de l'ACP dans le jeu de données de base
n_components = 3
for i in range(0, n_components):
    suggestion_df['PC' + str(i + 1)] = X_reduced[:, i]
```

Création d'un jeu de données plus petit, prenant 1000 produits aléatoirement pour chaque groupe de produits. Ainsi mon analyse ne sera pas biaisé par un nombre différent de produits par catégorie.

```{python}
df_light = suggestion_df.groupby("pnns_groups_1").sample(n=1000)

# Tri des données par energy (pour les représentations graphiques)
df_light = df_light.sort_values("energy_100g")
```

Analyse des cercles de corrélation des composantes principales. Je vais également observer la répartition des types de produit. Je pourrais être voir une répartition différentes en fonction des valeurs nutritives.

::: callout-note
Les points les plus intéressants sont généralement ceux qui sont assez proches d’un des axes, et assez loin de l’origine. Ces points sont bien corrélés avec cet axe et sont les points explicatifs pour l’axe : Ce sont les points les plus “parlants” ; leur “vraie distance” de l’origine est bien représentée sur le plan factoriel.
:::

Corrélations F1 et F2

```{python}
sns.set(font_scale=1.25)

correlation_graph(pca, (0, 1), col_100g)
```

Le cercle de corrélation confirme la corrélation entre saturated-fat_100g et fat_100g. Les produits sucrés sont bien représentés car proche de l'axe F2.

En projetant les produits par catégorie sur le même graphique on pourrait voir les groupes de produits sucrés séparés des produits gras.

```{python}
px.scatter(
    df_light,
    x="PC1",
    y="PC2",
    color="pnns_groups_1",
    title="Projection des groupes de produits sur les axes PC1 et PC2",
)
```

On distingue assez clairement les produits sucrés des produits plus gras. Au vue de la disposition des points il semble que les produits de type graisse et sauces sont à la fois sucrés et gras. Voyons la matrice de corrélation de PC1 et PC2.

```{python}

import plotly.express as px
import pandas as pd

# Calcul de la corrélation par groupe
df_corr = df_light.groupby("pnns_groups_1")["PC1"].corr(df_light["PC2"]).round(2).reset_index()
df_corr = df_corr.rename(columns={"PC1": "correlation"})  # Renommer pour éviter toute confusion

# Création du barplot coloré
fig = px.bar(
    df_corr,
    x="correlation",
    y="pnns_groups_1",
    text="correlation",
    color="correlation",
    color_continuous_scale="RdBu_r",
    range_color=[-1, 1],  # Définir l'échelle du gradient de couleur
    range_x = [-1,1],
    title="Corrélation de Spearman entre PC1 et PC2 par groupe de produit",
    orientation="h",  # Affichage horizontal pour meilleure lisibilité
    template="simple_white",
)

fig.update_traces(texttemplate="%{text:.2f}", textposition="outside")

fig.show()
```

Il n'y a pas de corrélation entre les composantes principales.

Voyons maintenant le cercle de corrélation F1 et F3.

```{python}
sns.set(font_scale=1.25)

correlation_graph(pca, (0, 2), col_100g)
```

Sur cette vue, c'est la teneur en fibre qui est bien représentée.

```{python}
px.scatter(
    df_light,
    x="PC1",
    y="PC3",
    color="pnns_groups_1",
    title="Projection des groupes de produits sur les axes PC2 et PC3",
)
```

## Relation entre les catégories et les valeurs énergétiques

```{python}
for col in col_100g:
    fig = px.histogram(
        suggestion_df,
        x="pnns_groups_1",
        y=col,
        color="pnns_groups_1",
        histfunc="avg",
        text_auto=".2f",
        title=f"Moyenne du taux de {col} par type de produit",
    )

    fig.update_layout(showlegend=False)  # Option pour cacher la légende si redondante
    fig.update_xaxes(matches=None)
    fig.update_yaxes(matches=None)
    fig.show()
```

## Analyse statistique

L'ANOVA est essentielle pour comprendre si certaines catégories alimentaires sont plus énergétiques que d'autres. Si de des différences sont détectées, on peut:

-   ✅ Faire des recommandations nutritionnelles.

-   ✅ Optimiser la classification des produits.

-   ✅ Identifier des groupes de produits particulièrement énergétiques.

### Pré-tests et vérifications

::: callout-note

Tests statistiques : ANOVA à un facteur\n Variable à expliquer (y) : Liste des variables composant le nutriscore\n Variable explicative (x) : energy_100g

Test des conditions d'application de l'ANOVA :\n 

- Indépendance des produits (individus)\n

- Les résidus doivent suivre une loi normal : Test de kolmogorov-smirnov\n

- La variance de chaque groupe doit être semblable : Test de bartlett

:::

#### Indépendance des observations

Je n'ai pas de produits en doublons dans mon jeu de données. Les observations sont indépendantes.

#### Normalité de la distribution

##### Approche empirique

Histogramme de fréquence, boxplot, coefficient de symétrie (skew),coefficient d'aplatissement (kurtosis), diagramme quantile-quantile (qq-plot).

```{python}
# histogram
tools.histogram_features(suggestion_df, ["energy_100g"])
```

```{python}
tools.visualiser_quartiles(suggestion_df, ["energy_100g"])
```

```{python}
skewness = suggestion_df["energy_100g"].skew()
kurtosis = suggestion_df["energy_100g"].kurtosis()

print(f"Skewness: {skewness:.3f}")
print(f"Kurtosis: {kurtosis:.3f}")
```

::: callout-note

- Si le skewness est proche de 0, la distribution est symétrique. 

- Si le skewness est \> 0, la distribution est asymétrique à droite.

- Si le skewness est \< 0, la distribution est asymétrique à gauche. Si le kurtosis est proche de 3, la distribution est normale. 

- Si le kurtosis est \> 3, la distribution a des queues plus épaisses que la normale. 

- Si le kurtosis est \< 3, la distribution est plus plate.

:::

Graphiquement, on peut voir que la distribution n'est pas normale mais bi-modale. Les coefficients d'asymétrie et d'aplatissement le confirme également.

```{python}
import statsmodels.api as sm
import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8-whitegrid")

sm.qqplot(suggestion_df["energy_100g"], line="s")
plt.title("QQ-Plot de energy_100g")
plt.show()
```

```{python}
import statsmodels.api as sm
import plotly.graph_objects as go

# Générer le QQ-Plot avec statsmodels (sans l'afficher)
fig_matplotlib = sm.qqplot(suggestion_df["energy_100g"], line="s")

# Récupérer les données du graphique Matplotlib
qqplot_data = fig_matplotlib.gca().lines

# Fermer le graphique Matplotlib pour éviter l'affichage Seaborn
plt.close()

fig = go.Figure()

fig.add_trace({
    "type": "scatter",
    "x": qqplot_data[0].get_xdata(),
    "y": qqplot_data[0].get_ydata(),
    "mode": "markers",
    "marker": {"color": "blue"},
})

fig.add_trace({
    "type": "scatter",
    "x": qqplot_data[1].get_xdata(),
    "y": qqplot_data[1].get_ydata(),
    "mode": "lines",
    "line": {"color": "red"},
})


fig["layout"].update({
    "title": "Quantile-Quantile Plot energy_100g",
    "xaxis": {"title": "Theoritical Quantities", "zeroline": False},
    "yaxis": {"title": "Sample Quantities"},
    "showlegend": False,
    "width": 500,
    "height": 500,
})

fig.show()

```

Le diagramme Quantile-Quantile confirme cette analyse. Les points s'écartent de la droite de référence aux extrémités, indiquant la présence de queues épaisses et une déviation de la normalité.

##### Approche statistique

```{python}
import pandas as pd
from scipy.stats import shapiro

# Définition de la fonction pour le test de Shapiro-Wilk
def shapiro_test(series):
    stat, p_value = shapiro(series.dropna())  # Ignorer les NaN
    return pd.Series({
        "stat": stat,
        "p_value": p_value,
        "valid_H0": p_value > 0.05,  # True si H0 est validé (données normales)
    })

# Application de la fonction sur chaque colonne et création du DataFrame
# shapiro_df = suggestion_df[col_100g].apply(shapiro_test).T

shapiro_df = shapiro_test(suggestion_df["energy_100g"])

# Affichage du résultat
show(shapiro_df, "Test de Shapiro-Wilk sur la colonne energy_100g")
```

Les valeurs nutritives ne valident pas l'hypothèse d'une distribution normale. La **statistique W** est éloignée de 1 sauf pour les valeurs énergétiques. La probabilité **p** en rejetant 0 est inférieures à 1%.

::: callout-caution

Le test de Shapiro-Wilk est sensible aux grands volumes de données (N \> 5000), il peut donc détecter des écarts minimes comme significatifs. Dans ce cas, mieux vaut aussi analyser le QQ-Plot. Je vérifie ce résultat avec le test de Kolmogorov-Smirnov et le test de d'Anderson-Darling.

:::

```{python}
from scipy.stats import kstest

feature = suggestion_df["energy_100g"]

stat, p = kstest(feature, "norm")

print(f"Test KS: statistic={stat}, p-value={p}")
```

Si p-value \< 0.05, la distribution n’est pas normale. La valeur statistic correspond à la plus grande différence entre la distribution empirique et la distribution normale théorique.
La valeur de p est inférieure à 0.05. Au moins un groupe à une moyenne différente des autres groupes. L'hypothèse H0 est réfutée.

::: callout-note
Le test d'Anderson-Darling est plus robuste pour des distributions asymétriques. C'est un cas particulier du test de Kolmogorov-Smirnov.\n
[plotly: normality-test](https://plotly.com/python/v3/normality-test/)
:::

Test Anderson-Darling

```{python}
from scipy.stats import anderson

feature = suggestion_df["energy_100g"]

result = anderson(feature, dist="norm")

print("Test d'Anderson-Darling pour la normalité")
print(f"Statistique AD : {result.statistic}")
for i in range(len(result.critical_values)):
    print(f"Seuil critique {result.significance_level[i]}% : {result.critical_values[i]}")
```

La statistique AD = 687.73 est largement supérieure à tous les seuils critiques. Même au seuil de 1% (1.092), la statistique est beaucoup trop grande. On rejette fortement l'hypothèse H₀ (normalité) à tous les niveaux de confiance.

On peut visualiser la fonction de répartition empirique.

```{python}
import plotly.express as px
import plotly.graph_objects as go
from scipy.stats import norm
import numpy as np

# Calcul de la moyenne et de l'écart-type
feature = suggestion_df["energy_100g"]

# Générer des valeurs suivant une distribution normale
mu, std = norm.fit(feature)
xmin = feature.min()
xmax = feature.max()

# Générer les valeurs pour la courbe normale
x_values = np.linspace(xmin, xmax, len(feature))

# Calcul de la densité de probabilité pour la distribution normale
pdf_values = norm.pdf(x_values, mu, std)

# Calcul de l'ECDF cumulée en intégrant la densité de probabilité
ecdf_normal = np.cumsum(pdf_values) * (x_values[1] - x_values[0])  # Cumsum pour simuler l'ECDF


fig = px.ecdf(
    suggestion_df,
    x="energy_100g",
    # ecdfnorm=None,
    marginal="histogram",
    title="Comparaison ECDF réelle vs normale",
)

# Ajouter la distribution normale en rouge
fig.add_trace(
    go.Scatter(
        x=x_values,
        y=ecdf_normal,
        mode="lines",
        name="ECDF Normale",
        line=dict(color="red", width=2, dash="dash"),
    )
)


fig.show()
```

Test de Bartlett

```{python}
from scipy.stats import bartlett

# Extraire les listes de valeurs pour chaque groupe
groups = [data["energy_100g"].values for _, data in suggestion_df.groupby("pnns_groups_1")]

# Appliquer le test de Bartlett
stat, p = bartlett(*groups)

# Affichage des résultats
print(f"Test de Bartlett: statistic={stat:.4f}, p-value={p:.4f}")

```

La valeur de p est inférieure à 0.05. Au moins un groupe à une variance différente des autres groupes. L'hypothèse H0 est réfutée.

Les conditions d'applications ne sont remplies pour aucune des variables

Equivalent non paramétrique de l'ANOVA : Test de kruskall Wallis

```{python}
from scipy.stats import kruskal

# Extraire les listes de valeurs pour chaque groupe
groups = [data["energy_100g"].values for _, data in suggestion_df.groupby("pnns_groups_1")]

# Appliquer le test de kruskal-Wallis
stat, p = kruskal(*groups)

# Affichage des résultats
print(f"Test de Kruskal-Wallis: statistic={stat:.4f}, p-value={p:.4f}")

```

::: {.callout-note}

Le test de Kruskal-Wallis utilise les hypothèses nulles et alternatives suivantes :

L’hypothèse nulle ($H_0$) : La médiane est égale dans tous les groupes.

L’hypothèse alternative : ($H_a$) : La médiane n’est pas égale dans tous les groupes.

:::

La valeur p est inférieure à 0. La médiane n'est pas égale pour toutes les catégories de produit. L'hypothèse $H0$ est rejetée.

```{python}
def calculate_eta_squared(df: pd.DataFrame, categorical_col: str, numerical_col: str) -> float:
    """
    Calcule l'ETA² (η²) pour mesurer l'effet d'une variable catégorielle sur une variable numérique.
    Le jeu de données ne doit pas contenir de valeurs manquantes.

    Paramètres :
    df : pd.DataFrame  -> Le DataFrame contenant les données.
    categorical_col : str  -> Le nom de la colonne catégorielle (facteur).
    numerical_col : str  -> Le nom de la colonne numérique (variable dépendante).

    Retourne :
    float -> La valeur de l'ETA².
    """
    # Calcul de la somme des carrés totale (sct)
    mean_total = df[numerical_col].mean()
    sct = ((df[numerical_col] - mean_total) ** 2).sum()

    # Calcul des effectifs et moyennes par groupe
    group_stats = df.groupby(categorical_col)[numerical_col].agg(ni="count", moyenne_groupe="mean").reset_index()

    sce = (group_stats["ni"] * (group_stats["moyenne_groupe"] - mean_total) ** 2).sum()

    # Calcul de l'ETA²
    eta_squared = sce / sct if sct > 0 else 0

    return eta_squared


for col in col_100g:
    eta = calculate_eta_squared(suggestion_df, "pnns_groups_1", col)

    print(f"Résultat de eta pour {col}: {eta:.2f}")
```

::: {.callout-note}

Les règles empiriques suivantes sont utilisées pour interpréter les valeurs de Eta au carré :

.01 : Petite taille d’effet
.06 : Taille d’effet moyenne
.14 ou supérieur : grande taille d’effet

:::

Le calcul du coefficient eta carré montre que pour chaque valeurs nutritives les catégories de produit sont bien différentes.

### Protection des données

::: {.callout-note}

Les 5 grands principes des règles de protection des données personnelles sont les suivants :

- Le principe de finalité : le responsable d'un fichier ne peut enregistrer et utiliser des informations sur des personnes physiques que dans un but bien précis, légal et légitime ;

- Le principe de proportionnalité et de pertinence : les informations enregistrées doivent être pertinentes et strictement nécessaires au regard de la finalité du fichier ;

- Le principe d'une durée de conservation limitée : il n'est pas possible de conserver des informations sur des personnes physiques dans un fichier pour une durée indéfinie. Une durée de conservation précise doit être fixée, en fonction du type d'information enregistrée et de la finalité du fichier ;

- Le principe de sécurité et de confidentialité : le responsable du fichier doit garantir la sécurité des informations qu'il détient. Il doit en particulier veiller à ce que seules les personnes autorisées aient accès à ces informations ;

- Les droits des personnes.

:::

Le jeu de données utilisé ne contient pas de données utilisateur. Il n'y a pas de risques juridiques liés à la RGPD.

## Conclusion

Dimension du jeu de données: 40428 produits, 7 valeurs nutritives

Nombre de produits hétérogènes par catégories avec une prédominance des produits sucrés.

Les groupes sont distincts les uns des autres ce qui devrait réduire le nombre de fausses suggestions.


```{python}
tools.save_processed_data(suggestion_df, "save_final_data")
```