# start mlflow server
[group('ml-tools')]
start-mlflow:
    uv run mlflow server \
    --backend-store-uri sqlite:///data/mlflow/db/mlflow.db \
    --default-artifact-root file:data/mlflow/artifacts
    --host 127.0.0.1 \
    --port 5000

@_:
    just --list

# Run linters
[group('qa')]
lint:
    uvx ruff check
    uvx ruff format

# Check types
[group('qa')]
typing:
    uvx ty check --python .venv src

# Perform all checks
[group('qa')]
check-all: lint typing

# Update dependencies
[group('lifecycle')]
update:
    uv sync --upgrade

# Ensure project virtualenv is up to date
[group('lifecycle')]
install:
    uv sync

# Remove temporary files
[group('lifecycle')]
clean:
    rm -rf .venv .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov
    find . -type d -name "__pycache__" -exec rm -r {} +

# Recreate project virtualenv from nothing
[group('lifecycle')]
fresh: clean install
