---
title: "Projet 2"
subtitle: "Préparer les données pour un organisme de santé publique"
author: "Guillaume LAFON"

format:
  pptx:
    incremental: true 
    toc: true
    top-depth: 1
    toc-title: "Sommaire"
    reference-doc: template.pptx
lang: fr
output: false
---

## Introduction

### Contexte

Proposer une méthode d'autocompletion pour ajouter les informations d'un produit dans la base de données Open Food Fact de l'Agence de santé Française.\n
**Mon objectif**: Obtenir un jeu de données complet, représentatif des différents types de produits, et prêt à être exploité par un algorithme de suggestion, sans valeurs nutritionnelles manquantes.

### Données

Je de données sur les produits alimentaires du monde entier. Base de données issue de OpenFoodFacts

### Mission

Pré-Analyse exploratoire des données pour:

- Nettoyer et explorer les données en interne,

- Déterminer la faisabilité de cette idée d’application de Santé publique France.

## Exploration du jeu de données

## Sélection des caractéristiques

## Analyse exploratoire

### Faits pertinents pour l'application
