project:
  type: default
  output-dir: _output
  preview:
    port: 7669
    browser: false
output-dir: _output
other-links:  
  - text: laguill
    href: https://github.com/laguill/

editor:
  render-on-save: false

execute:
  enabled: true
  cache: true
  freeze: auto

css: style.css

toc: true
toc-location: left-body
toc-depth: 4
number-sections: true
lang: fr
format:
  html:
    code-fold: true
    toc: true
    toc-expand: true
    number-sections: true
    theme:
      light: flatly
      dark: darkly 
    embed-resources: true
    page-layout: full
    output-file: LAFON_Guillaume_web-page_012025.html
    
  ipynb: 
    echo: true
    output-file: LAFON_Guillaume_notebook_012025.ipynb

ipynb-shell-interactivity: all
jupyter:
  jupytext:
    formats: 'qmd:quarto,py'
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.4
  kernelspec:
    display_name: Python (Pixi)
    language: python
    name: pixi-kernel-python3

render:
  - "*.qmd"

