project:
  execute-dir: project
  type: book
  output-dir: _output
  preview:
    port: 7669
    browser: false

metadata-files:
  - _book.yml


editor:
  render-on-save: false

execute:
  enabled: true
  cache: true
  freeze: auto

css: style.css

lang: fr
format:
  html:
    comments:
      hypothesis: false
    code-fold: true
    code-copy: true

    theme:
      light: flatly
      dark: darkly 
    embed-resources: false
    self_contained: false
    page-layout: full
    # output-file: LAFON_Guillaume_web-page_012025.html
    
#   ipynb: 
#      echo: true
#   #   output-file: LAFON_Guillaume_notebook_012025.ipynb

# ipynb-shell-interactivity: all

render:
  - "*.qmd"
 

