---
title: Introduction
subtitle: Analyse de la base de données Open Food Fact de l'Agence de santé Française
authors:
  - name: Guillaume LAFON
    affiliation: OpenClassrooms
    email: guillaumelafon13@gmail.com
date: last-modified
number-sections: false
abstract: |
    - **But de la mission** : 
    
    Proposer une méthode d'autocompletion pour ajouter les informations d'un produit dans la base de données Open Food Fact de l'Agence de santé Française.\n
    Pour ce projet, je suis chargé de nettoyage et explorer les données en interne, afin de déterminer la faisabilité de cette idée d’application de Santé publique France.

    - **Détails de la mission** :

    1. Analyser le jeu de donnant en repérant les variables pertinentes.
    2. Nettoyer les données en mettant en évidence les valeurs manquantes et/ou aberrantes.
    3. Automatiser ce filtrage
    4. Produire des visuels graphiques de comparaison de variables
    5. Rédiger un rapport d'exploration et une conclusion sur la faisabilité du projet
    6. Proposer un visuel/FAQ sur le respect de la RGPD

categories:
  - Open Food Fact
  - OpenClassrooms
  - Agence de santé publique

---

## Definition des acteurs

- **Santé publique France**: 

Santé publique France est l’agence nationale de santé publique. Créée en mai 2016 par ordonnance et décret, c’est un établissement public administratif sous tutelle du ministère chargé de la Santé.\n
Leur mission : améliorer et protéger la santé des populations.\n
Cette mission s'articule autour de trois axes majeurs : anticiper, comprendre et agir.

- **OpenFoodFact**:

Open Food Facts est une base de données collaborative de produits alimentaires avec leurs ingrédients, allergènes, valeurs nutritionnelles et toutes les juteuses informations que l'on peut trouver sur les labels de ces produits.

- **Nutri-Score**:

Le Nutri-Score permet de comparer les produits d’un même rayon, comme les céréales du petit-déjeuner, pour choisir ceux avec la meilleure qualité nutritionnelle.\ 
Il aide également à comparer un même produit de différentes marques, comme les lasagnes à la bolognaise, et à évaluer des produits consommés à la même occasion, comme les desserts.
([brochure nutri-score](https://www.mangerbouger.fr/Media/guides-et-documents/nutri-score/brochure-nutri-score3))

La notation prend en compte, pour 100 grammes de produit, la teneur :

- en nutriments et aliments à favoriser : fibres, protéines, fruits et légumes, légumes sec…

- en nutriments à limiter : calories, acides gras saturés, sucres, sel

Le Nutri-Score utilise une échelle de notation allant de A à E pour évaluer la qualité nutritionnelle des produits alimentaires. A étant la meilleure qualité nutritionnelle et E la moins bonne.

:::: {.callout-note}
Pour le moment, le Nutri-Score ne prend pas en compte les additifs ni les pesticides.
:::

## Formulation de la problématique

L’agence Santé publique France confie à votre entreprise la création d’un système de suggestion ou d’auto-complétion pour aider les usagers à remplir plus efficacement la base de données de OpenFoodFact.

1. Nettoyer et explorer les données.
2. Sélectionner les champs de données pertinents pour caractériser un produit.